apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: Sample
  name: Sample
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Sample-1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: Sample-1
    spec:
      containers:
      - image: {{ARTIFACTORY_IP}}:{{ARTIFACTORY_PORT}}/{{ARTIFACTORY_KEY}}/{{IAMGE_NAME}}:{{TAG_NAME}}
        name: maven-project1-c1
        imagePullPolicy: Always
        resources: {}
      imagePullSecrets:
          - name: regcred
status: {}

